export const topics = [
  "Number Systems",
  "Operations with Numbers",
  "Order of Operations (PEMDAS)",
  "Exponents and Radicals",
  "Algebraic Expressions & Equations",
  "Inequalities",
  "Functions",
  "Linear Relationships & Slope",
  "Systems of Linear Equations",
  "Matrices & Determinants",
  "Polynomials",
  "Geometry Basics",
  "Perimeter, Area, and Volume",
  "Pythagorean Theorem & Trigonometry",
  "Circles and Their Properties",
  "Similarity and Congruence",
  "Probability & Statistics",
  "Logic and Set Theory",
  "Logic Puzzles and Brainteasers",
  "Real-World Applications of Mathematics",
  "History of Mathematics",
  "Famous Mathematical Problems",
  "Number Theory & Prime Numbers",
  "Combinatorics and Permutations",
  "Sequences and Series",
  "Limits and Continuity",
  "Derivatives and Applications",
  "Integrals and Applications",
  "Statistics and Probability Distributions",
  "Linear Algebra and Applications",
];
